server.port: 8083

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKASERVER_URI:http://localhost:8761/eureka/}
  healthcheck:
      enabled: true

providerUrl: ${PROVIDER_URL:http://localhost:1080/sendsms}
